"""Additive, disabled apply/boot scaffold for the sing-box TProxy path.

Status
------
Scaffold only. ``tproxy.enabled=True`` is still rejected before it ever reaches
this module: :class:`~vs_router.schema.ConfigurationVersion` runs
:func:`validators.validate_configuration`, which fails with
``tproxy.not_available`` (``validators.py``). A version that *is* enabled can
only exist as an offline ``model_copy`` snapshot (the same idiom the offline
generators use). Therefore every branch in this module is **unreachable from any
valid configuration**, and for ``enabled=False`` it contributes nothing: no
extra file, no extra validator, no extra marker key, no extra phase. Current
``apply``/``boot`` behaviour is byte-for-byte unchanged for those inputs.

What this module is
-------------------
The data contract that :mod:`vs_router.agent.apply` and
:mod:`vs_router.agent.boot_restore` consume *conditionally* once the public gate
opens. It renders no new content of its own: guard text comes byte-for-byte from
the existing offline nftables generators, and the engine file from
:func:`generators.singbox.generate_singbox`.

Order contract (must not be reordered)
--------------------------------------
The plan (``docs/sing-box-tproxy-plan.md`` §«1. Контракт и контролируемый
процесс») requires that traffic is never captured before the fail-closed state
exists. Expressed as ordered phases::

    1. guards      — protective nftables tables (containment + preauthorization
                     + DNS guards) are installed BEFORE anything routes through
                     the TProxy tract. If these do not load, nothing else runs.
    2. readiness   — the DNS-contour resolver configs (selected/ordinary Unbound)
                     and the sing-box artifact are staged and validated so the
                     engine is known-present before interception is authorized,
                     then both resolver processes and the engine are started and
                     proven ready. The split configs come from ADR-0014; the
                     typed steps stage the files and start the two Unbound
                     processes (:mod:`agent.unbound_service`) and the engine
                     (:mod:`agent.singbox_service`), each fail-closed.
    3. interception— the capture rules (mark / redirect) that divert selected
                     traffic. Generated by
                     :func:`generators.nftables.generate_tproxy_interception`
                     and installed strictly after the guards and the readiness
                     artifact, so traffic is never captured before the
                     fail-closed state exists.
    4. compensation— on any failure the previously confirmed target is
                     reinstalled and every TProxy-owned table is explicitly
                     destroyed (:func:`cleanup_content`), so a half-open guard
                     or interception is never left behind.

Everything is data: file names, ordered phases, generator calls and nftables
text. No arbitrary shell, no new subprocess surface, no secret material.
"""

from __future__ import annotations

import json

from ..generators import marks
from ..generators import tproxy_dns
from ..generators.nftables import (generate_tproxy_containment,
                                   generate_tproxy_interception,
                                   generate_tproxy_ipv6_guard,
                                   generate_tproxy_preauthorization)
from ..generators.singbox import generate_singbox
from ..schema import ConfigurationVersion

#: TProxy-owned artifacts that participate in the ordinary apply file map.
#: Insertion order is the activation order and MUST stay guards-before-readiness-
#: before-capture: the protective tables load first, the two split resolver
#: configs (with the selected UID) and the engine artifact are staged/validated
#: second, and only then is the capture table installed.
#:
#: The DNS contour (ADR-0014) adds two readiness artifacts — the *selected* and
#: *ordinary* Unbound configs — plus the DNS OUTPUT guard inside ``tproxy_guards``.
#: Every DNS value (listener addresses, UID, tables) is composed by
#: :func:`generators.tproxy_dns.plan_tproxy_dns` so apply cannot drift from the
#: offline contour.
TPROXY_FILES: dict[str, str] = {
    "tproxy_guards": "tproxy-guards.nft",
    "tproxy_unbound_selected": "tproxy-unbound-selected.conf",
    "tproxy_unbound_ordinary": "tproxy-unbound-ordinary.conf",
    "singbox": "singbox.json",
    "tproxy_interception": "tproxy-intercept.nft",
}

#: Readiness artifacts of the DNS contour: the two split resolver configs. Data
#: only — no service is started and no UID/user is created (ADR-0014).
TPROXY_UNBOUND_FILES: tuple[str, ...] = ("tproxy_unbound_selected",
                                         "tproxy_unbound_ordinary")

#: Validators for the scaffold artifacts. ``nft -c -f`` is the same native check
#: the product firewall uses; the resolver configs use the same check the
#: ordinary Unbound bundle uses. The sing-box config check is the intended
#: pinned validator; the binary is not chosen/pinned yet (ADR-0012), so no live
#: apply may rely on it. Tests inject their own validators.
TPROXY_VALIDATORS: dict[str, list[str]] = {
    "tproxy_guards": ["nft", "-c", "-f"],
    "tproxy_unbound_selected": ["unbound-checkconf"],
    "tproxy_unbound_ordinary": ["unbound-checkconf"],
    "singbox": ["sing-box", "check", "-c"],
    "tproxy_interception": ["nft", "-c", "-f"],
}

#: Rollback-only teardown artifact: destroy every TProxy-owned table.
TPROXY_CLEANUP_FILE = "tproxy-cleanup.nft"
TPROXY_CLEANUP_VALIDATOR: list[str] = ["nft", "-c", "-f"]

#: Ordered phases; see the module docstring. The tuple-of-pairs form makes the
#: order explicit and testable. ``guards`` carries the protective tables *and*
#: the DNS OUTPUT boundary; ``readiness`` carries both split resolver configs and
#: the engine artifact; ``interception`` carries the capture artifact and is
#: installed strictly after the guards and the readiness artifacts. Every phase
#: is reachable only from an (offline) enabled configuration.
PHASE_ORDER: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("guards", ("tproxy_guards",)),
    ("readiness", ("tproxy_unbound_selected", "tproxy_unbound_ordinary", "singbox")),
    ("interception", ("tproxy_interception",)),
)

#: Typed, non-file readiness steps. They carry no artifact and add no key to
#: :data:`TPROXY_FILES`; ``apply`` runs them after the readiness files and
#: strictly before ``tproxy_interception``, so the routing table, both DNS
#: resolvers and the engine process are in place before traffic can ever be
#: captured. The policy-route step installs the owned ``ip rule``/``ip route``
#: (:mod:`agent.policy_route`); the engine step starts the pinned engine and
#: proves readiness (:mod:`agent.singbox_service`); the resolver step starts the
#: two Unbound processes of the DNS contour and proves readiness
#: (:mod:`agent.unbound_service`) — both resolvers must be up before capture.
POLICY_ROUTE_STEP = "tproxy_policy_route"
SINGBOX_PROCESS_STEP = "singbox_process"
UNBOUND_PROCESS_STEP = "unbound_process"
READINESS_STEPS: tuple[str, ...] = (POLICY_ROUTE_STEP, UNBOUND_PROCESS_STEP,
                                    SINGBOX_PROCESS_STEP)

#: Compensation order (reverse of activation): stop the engine, stop the two
#: resolvers, then remove the owned policy route. The generated ``destroy table``
#: text cannot do any of those.
TEARDOWN_STEPS: tuple[str, ...] = (SINGBOX_PROCESS_STEP, UNBOUND_PROCESS_STEP,
                                   POLICY_ROUTE_STEP)


def required(version: ConfigurationVersion) -> bool:
    """True only for an (offline) enabled configuration; False for everything
    reachable through the public contract."""
    return bool(version.configuration.tproxy.enabled)


def owned_tables() -> tuple[str, ...]:
    """Every nftables table owned by the TProxy path.

    Derived from the single ownership registry (:mod:`generators.marks`) so the
    teardown list cannot drift from the tables the guards actually create.
    """
    return tuple(table.name for table in marks.TABLES if not table.wired)


def plan(version: ConfigurationVersion):
    """Compose the offline DNS contour for ``version``.

    Single entry point the scaffold uses so guard tables and resolver configs are
    always generated from the same plan: listener addresses from the
    configuration validator, the selected UID from
    :func:`generators.tproxy_dns.selected_uid_for`. Raises the planner's
    ``ValueError`` (e.g. ``tproxy.dns_output_invalid_uid``,
    ``tproxy.dns_split_missing_listener``) — failing closed rather than emitting
    a partial contour.
    """
    return tproxy_dns.plan_tproxy_dns(version, tproxy_dns.selected_uid_for(version))


def guard_content(version: ConfigurationVersion) -> str:
    """Render the protective nftables text (phase 1).

    Concatenation of the existing offline generators, in the order a packet
    sees them: FORWARD containment (priority -10), the FORWARD IPv6-WAN-escape
    guard (-11), PREROUTING preauthorization (-90) and the three DNS guards from
    :func:`plan` -- PREROUTING ingress (-110), INPUT listener boundary (-10) and
    the UID-scoped OUTPUT boundary (-20). Each generator already returns its own
    ``destroy table`` header, so the file is idempotent and valid ``nft -f``
    input.

    The DNS guards (including OUTPUT, which needs the selected UID) come
    byte-for-byte from :func:`plan`, so the phase-1 text and the resolver configs
    cannot disagree about listeners, tables or UID.
    """
    return (
        generate_tproxy_containment(version)
        + generate_tproxy_ipv6_guard(version)
        + generate_tproxy_preauthorization(version)
        + "".join(guard.content for guard in plan(version).nft_guards)
    )


def build_artifacts(version: ConfigurationVersion) -> dict[str, str]:
    """Return ``{name: content}`` for the scaffold files, or ``{}`` when off.

    Keys match :data:`TPROXY_FILES` and preserve its order (guards, the two
    readiness resolver configs, engine, capture). Called by apply only for an
    enabled version; empty otherwise.
    """
    if not required(version):
        return {}
    composed = plan(version)
    return {
        "tproxy_guards": guard_content(version),
        "tproxy_unbound_selected": composed.selected_unbound or "",
        "tproxy_unbound_ordinary": composed.ordinary_unbound or "",
        "singbox": json.dumps(generate_singbox(version), indent=2) + "\n",
        "tproxy_interception": generate_tproxy_interception(version),
    }


def cleanup_files() -> tuple[str, ...]:
    """Filenames of the TProxy readiness artifacts to remove on teardown.

    Destroy-only nftables text cannot remove a resolver config file, so a
    rollback/teardown must also unlink them; otherwise a half-open apply would
    leave the split configs of an aborted contour on disk.
    """
    return tuple(TPROXY_FILES[name] for name in TPROXY_UNBOUND_FILES)


def teardown_files() -> tuple[str, ...]:
    """Filenames of every TProxy artifact to unlink on teardown.

    Everything except the boot-loaded guard, which must instead be *overwritten*
    with :func:`cleanup_content` (destroy-only): ``boot_restore`` loads the guard
    file first on every boot, so an abandoned apply that left the protective
    guard text there would re-raise fail-closed tables on a non-TProxy confirmed
    state. The other artifacts (resolver configs, engine JSON, capture table)
    have no place in a non-TProxy state and are unlinked.
    """
    return tuple(filename for name, filename in TPROXY_FILES.items()
                 if name != "tproxy_guards")


def cleanup_content() -> str:
    """Destroy-only nftables text removing every TProxy-owned table (phase 4).

    Safe to run against a host where none exist: ``destroy table`` on an absent
    table is a no-op. Used as compensation when the confirmed target is not a
    TProxy state but an interrupted apply had already written guard/interception
    artifacts, so the tract is torn down rather than left partially open.
    """
    return "".join(f"destroy table {name}\n" for name in owned_tables())


def describe(version: ConfigurationVersion | None = None) -> dict:
    """JSON-serializable plan recorded in the apply marker when enabled.

    With ``version`` (the apply path) the marker also records the deterministic
    selected UID and the readiness resolver set, so the marker explains the DNS
    contour identity, not only the file list.
    """
    data = {
        "required": True,
        "phase_order": [[phase, list(names)] for phase, names in PHASE_ORDER],
        "files": list(TPROXY_FILES),
        "readiness_steps": list(READINESS_STEPS),
    }
    if version is not None:
        uid = tproxy_dns.selected_uid_for(version)
        ordinary_uid = tproxy_dns.ordinary_uid_for(version)
        data["selected_uid"] = uid
        data["ordinary_uid"] = ordinary_uid
        data["readiness"] = {"selected_uid": uid, "ordinary_uid": ordinary_uid,
                            "resolvers": list(TPROXY_UNBOUND_FILES)}
    return data
